version: "3"

services:
  kononobot-service:
    build:
      context: .
      dockerfile: Scraper.Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: "postgres"
    hostname: "${POSTGRES_HOSTNAME}"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  docker-entrypoint-initdb.d:
